### PR TITLE
extra fluent API methods for tasks (#34 #35)

### LINKED ISSUE #34: With(params string[] args)
Spun off from #31

### LINKED ISSUE #35: Pack.Properties(object)
Spun off from #31

``` C#
pack
    .Properties(new { Configuration = "Release"})
```

### PR DESCRIPTION
**Pull request by aarondandy**
Some fluent API changes to make working with the plugin a bit easier and future-proof.

closes #34 
closes #35

### CODE REVIEW

**Comment by aarondandy** [comment]
The CI actually failed. Try it locally to see if it works for real. Both CI systems are not doing so well.

**Comment by adamralph** [comment]
I've raised https://github.com/bau-build/bau-nuget/issues/39 to fix the builds for scriptcs 0.13.

I've also raised https://github.com/bau-build/bau-nuget/issues/40 to get the AppVeyor build status showing up on PR's again.

Unfortunately TravisCI will continue to suffer from mono failing to propagate non-zero exit codes :unamused:

**Comment by aarondandy** [comment]
This PR is waiting for #38 so we can test the CI. There is no hurry on this PR, it only needs to come before scriptcs 1.0 .

**Comment by adamralph** [comment]
Yep, I'll get back on #38 ASAP. Shouldn't take too long.

**Comment by aarondandy** [comment]
Would it be OK if i merged PR #38 into this? These commits expect scriptcs < 0.13.0

**Comment by adamralph** [comment]
I'd prefer if you didn't. I think we should fix that as a separate issue and not mix it into this. This branch can be rebased onto dev after it gets the 0.13 fix.

I don't have time to get back on to https://github.com/bau-build/bau-nuget/issues/39 right now so if you want to take it over in the meantime and send a superseding PR to #38 then feel free.

**Comment by aarondandy** [comment]
Not to be merged until rebased against fixes for #39

**Comment by adamralph** [comment]
We really need to fix https://github.com/bau-build/bau-nuget/issues/40 and then we'd see that this doesn't build on appveyor.

**Comment by adamralph** [comment]
@aarondandy please assign back to me after the appveyor build is green.

**Comment by adamralph** [comment]
This can be rebased now.

**Comment by aarondandy** [comment]
Already did it. Testing locally first.

**Comment by adamralph** [comment]
LGTM. The only thing I'd change is to rename `ExtraArgs` to `Args`, to align with Bau.MSBuild and Bau.Xunit.

**Comment by adamralph** [comment]
Thanks, nice work!

**Comment by aarondandy** [comment]
:pray: High five, milestone done!

**Comment by adamralph** [comment]
I've just added the mono bug to it :grimacing:

**Pull request merged**
