### PR TITLE
docs: add readme

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
To see how it looks - https://github.com/adamralph/bau-nuget/blob/readme/README.md

**Comment by adamralph** [comment]
Usage to be added after we've finalised the API.

**Comment by aarondandy** [comment]
For those of us without NuGet.exe on the path, should the readme also mention `scriptcs -install NuGet.CommandLine` ?

**Comment by aarondandy** [comment]
Am I the only one?

**Comment by adamralph** [comment]
Good point. Added.

**Pull request merged**
