### PR TITLE
refactor: prepare for travisci

### LINKED ISSUE #18: CI build
Either http://teamcity.codebetter.com/ or https://ci.appveyor.com/. We could also try for a Mono build on https://travis-ci.org/ but I'm not sure how well NuGet.exe plays on *nix these days.
- [x] appveyor
- [x] travisci

### PR DESCRIPTION
**Pull request by adamralph**
closes #18

### CODE REVIEW

**Comment by aarondandy** [comment]
So did both run on this? GitHub is being very confusing about this.

**Comment by adamralph** [comment]
Yeah it's a shame, but GitHub can't handle multiple build status. I heard a rumour they were going to add it but I haven't seen any movement yet. Unfortunately it does mean you need to check the build which isn't shown manually.

**Comment by adamralph** [comment]
So the travis ci build passes, but 2 unit tests fail because we do have a genuine problem running on Mono. I'll spin off a separate bug for this.

The failure of the exit code to propagate and fail the build is a problem with scriptcs, and thus Bau, on Mono.

**Comment by aarondandy** [comment]
But it has the colors!

**Comment by adamralph** [comment]
Yeah, Travis plays nicely with console colours :lipstick: 

Spun off #30 for the Mono bug.

**Comment by adamralph** [comment]
@aarondandy I think this should go in now (assuming you're happy with the implementation). That way we'll know that we've fixed #30 when the tests pass on Travis.

**Pull request merged**
